### ISSUE TITLE
Bugfixes 13-05-2023

### ISSUE THREAD

**Issue by Antalyan** [Antalyan/riddleshare#42]
**TODO**

**In progress**
- [x] FetchUserRiddleInfos nevracet undefined, ale být konzistentní s ostatními
- [x] Updatovat kopírovaný link na celou adresu tzn. včetně prefixu
- [x] Zakomentovat obrázková pole pro otázky, aby se nezobrazovala při vytváření hádanky
- [x] Přidat autora hádanky do preview
- [x] Neukládat hesla v plaintextu
- [x] Zobraz název aktuálně přihlášeného uživatele někde (main page + hlavička?)
- [x] Pokud zadám přímo do url nějaké random linkId (`/riddle-detail/123456789`), tak mě to nepřesměruje na `/not-found`
- [x] Přeformátovat text v detailu, aby bylo vidět, že jde o text hádanky (přidat označení Text hádanky?) => jen zvětšeno písmo
- [x] Vyřešit kolizi dvou difficulty typů (aktuálně se dědí _difficulty_ z _RiddlePreview_, ale přidává se i další _difficultyValue_
- [x] Udělat vybraná formulářová pole povinná
- [x] Fixnout mock data
- [x] Sjednotit používání typu `Props` (někde je `FC<Props>` a někde `{ ... }: Props`)
- [x] Při chybě autentizace (např. kliknutí na signup, i když je uživatel zaregistrovaný) by se uživatel neměl duplicitně uložit do databáze ani být přesměrován na homepage
- [x] Povolit update hádanky (pozor na to, co povolíme měnit: neměnit počet otázek)
- [x] Povolit autorovi smazání hádanky
- [x] Udělat stránku s public hádankami a jejich detailem veřejné (možnost řešení nikoliv)
- [x] Hláška uživateli při (ne)úspěšném vkládání hádanky
- [x] Barva načítací okna a pozadí pro autocomplete-userstosharewith s multiple options
- [x] Improve logging: add more log entries about what happened
- [x] Responsivity checks
- [x] Validovat velikost souboru
- [x] Přidat `CircularProgress` z MUI tam, kde dává smysl
